#!/bin/sh

## functions ##
log_help(){
	less $path/.help
	exit
}

log_edit(){
	nano $file
}

log_show_all(){
	ls $path
	exit
}

log_show(){
	less $file
}

log_delete(){
	echo -e "Zeker dat je deze log file wil deleten? Ze zal nergens meer te vinden zijn...  \n"
	rm -i $file
}

log_new_edit(){
	echo "========== [" $when "] ==========" >>  $tempfile
	echo -e "\n" >> $tempfile
	cp $file $file"2"
	cat $tempfile $file"2" > $file
	nano $file
	rm $file"2" $tempfile
}

log_normal(){
	echo "========== [" $when "] ==========" >>  $tempfile
	nano $tempfile
	echo -e >> $tempfile
	cp $file $file"2"
	cat $tempfile $file"2" >  $file
	rm $file"2" $tempfile
}


## main code ##

path="/home/admin/.logs"


file=$path/$1.log
tempfile=$path/$1.temp.log
when=$(date +"%A-%d/%m/%Y-%H:%M")

if [ ! -z $1 ]; then
	case $1 in
		help)
			log_help
			;;
		-S)	
			log_show_all
			;;
		*)
			[ ! -f $path/$1.log  ] && touch $path/$1.log
			;;
	esac
else
	echo "Geef naam van logfile in."
	exit
fi


if [ ! -f $2  ]; then
	case $2 in
		-e)
			log_edit $1
			;;
		-s)	
			log_show $1
			;;
		-ne)
			log_new_edit $1
			;;
		-d)
			log_delete $1
			;;
	esac
else
	log_normal $1
fi
