#!/bin/sh

## functions ##
qn_help(){
	less '/usr/bin/.help'
	exit
}

qn_edit(){
	nano $file
}

qn_show_all(){
	ls $path
	exit
}

qn_show(){
	less $file
}

qn_delete(){
	echo "Are you sure you want to delete this note?  \n"
	rm -i $file
}

qn_new_edit(){
	echo "========== [" $when "] ==========" >>  $tempfile
	echo "\n" >> $tempfile
	cp $file $file"2"
	cat $tempfile $file"2" > $file
	nano $file
	rm $file"2" $tempfile
}

qn_normal(){
	echo "========== [" $when "] ==========" >>  $tempfile
	nano $tempfile
	echo "\n" >> $tempfile
	cp $file $file"2"
	cat $tempfile $file"2" >  $file
	rm $file"2" $tempfile
}

assign_dir(){
		mkdir $1 && 
		cp ~/.bashrc $1 &&
		echo "export qn_path=$1" >> ~/.bashrc &&
		echo "Made dir $1, made a copy of .bashrc, and stored it in $1. And exported qn_path=$1 onto .bashrc"
}

## main code ##
# path=$qn_path
path='~/.quickNotes'
file=$path/$1
tempfile=$path/$1.temp
when=$(date +"%A-%d/%m/%Y-%H:%M")

if [ ! -z $1 ]; then
	case $1 in
		help)
			qn_help
			;;
		-S)
			qn_show_all
			;;
		'-dir')
			[ ! -d $2 ] && assign_dir $2 ||
			echo 'dir already exists'
			;;
		*)
			[ ! -f $path/$1  ] && touch $file
			;;
	esac
else
	echo "Give a filename"
	exit
fi


if [ ! -f $2  ]; then
	case $2 in
		-e)
			qn_edit $1
			;;
		-s)
			qn_show $1
			;;
		-ne)
			qn_new_edit $1
			;;
		-d)
			qn_delete $1
			;;
	esac
else
	qn_normal $1
fi
