#!/bin/sh

## functions ##
qn_help(){
	less $path/.help
	exit
}

qn_edit(){
	nano $file
}

qn_show_all(){
	ls $path
	exit
}

qn_show(){
	less $file
}

qn_delete(){
	echo -e "Zeker dat je deze file wil deleten? Ze zal nergens meer te vinden zijn...  \n"
	rm -i $file
}

qn_new_edit(){
	echo "========== [" $when "] ==========" >>  $tempfile
	echo -e "\n" >> $tempfile
	cp $file $file"2"
	cat $tempfile $file"2" > $file
	nano $file
	rm $file"2" $tempfile
}

qn_normal(){
	echo "========== [" $when "] ==========" >>  $tempfile
	nano $tempfile
	echo -e >> $tempfile
	cp $file $file"2"
	cat $tempfile $file"2" >  $file
	rm $file"2" $tempfile
}


## main code ##
userHome="$HOME"
path="$userHome/.QuickNotes"


file=$path/$1
tempfile=$path/$1.temp
when=$(date +"%A-%d/%m/%Y-%H:%M")

if [ ! -z $1 ]; then
	case $1 in
		help)
			qn_help
			;;
		-S)
			qn_show_all
			;;
		*)
			[ ! -f $path/$1  ] && touch $path/$1
			;;
	esac
else
	echo "Geef naam van file in."
	exit
fi


if [ ! -f $2  ]; then
	case $2 in
		-e)
			qn_edit $1
			;;
		-s)
			qn_show $1
			;;
		-ne)
			qn_new_edit $1
			;;
		-d)
			qn_delete $1
			;;
	esac
else
	qn_normal $1
fi
