#!/bin/sh

## functions ##
qn_help(){
	less '/usr/bin/.help'
	exit
}

qn_edit(){
	$EDITOR $file
}

qn_show_all(){
	ls $path
	exit
}

qn_show(){
	less $file
}

qn_delete(){
	echo "Are you sure you want to delete this note?  \n"
	rm -i $file
}

qn_new_edit(){
	echo "========== [" $when "] ==========" >>  $tempfile
	echo "\n" >> $tempfile
	cp $file $file"2"
	cat $tempfile $file"2" > $file
	$EDITOR $file
	rm $file"2" $tempfile
}

qn_normal(){
	echo "========== [" $when "] ==========" >>  $tempfile
	$EDITOR $tempfile
	echo "\n" >> $tempfile
	cp $file $file"2"
	cat $tempfile $file"2" >  $file
	rm $file"2" $tempfile
}

assign_dir(){
		mkdir $1 && 
		cp ~/.bashrc $1 &&
		echo "export qn_path=$1" >> ~/.bashrc &&
		echo "Made dir $1, made a copy of .bashrc, and stored it in $1. And exported qn_path=$1 onto .bashrc"
}

## main code ##

#main variables
path='/home/'$USER'/.quickNotes'
tempfile=$path/$1.temp
when=$(date +"%A-%d/%m/%Y-%H:%M")

#check if there are arguments
if [ $# = 0 ]; then
	echo "Give a filename"
	exit
fi

#check what action must be performed
action="normal"

#loop over all arguments
for i in $@
do
	case $i in
		help)
			qn_help
			exit	
			;;
		-S)
			qn_show_all
			exit
			;;
		'-dir')
			[ ! -d $2 ] && assign_dir $2 ||
			echo 'dir already exists'
			;;
		-e)	
			action="edit"
			;;
		-ne)
			action="new_edit"
			;;
		-d)
			action="delete"
			;;
		*)
			file=$path/$i
			[ ! -f $path/$i  ] && touch $path/$i
			;;		
	esac
done

#check if a file is mentioned
if [ -z $file ]; then
	echo "Give a filename"
	exit
fi

#execute said action
case $action in
	normal)
		qn_normal
		;;
	edit)
		qn_edit
		;;
	new_edit)
		qn_new_edit
		;;
	delete)
		qn_delete
		;;
	*)
		echo "Something went wrong"
		;;
esac
